### ISSUE TITLE
How to clean up after 'attack'

### ISSUE THREAD

**Issue by wikijm** [NextronSystems/APTSimulator#11]
Hi @Neo23x0,

Thanks for your wonderful project, very useful to test https://github.com/Cyb3rWard0g/HELK project (Hunting ELK).

Is it possible to get help with a post-cleanup process?

For example, I have been able to delete one of the WMI Backdoor, but one is still active.

For the first one:
> Get-WMIObject -Namespace root\Subscription -Class __EventFilter -Filter "Name='LaunchBeaconingBackdoor'"

I am well aware that if the WMI Backdoor request is related to https://github.com/mattifestation/WMI_Backdoor project, my request is for your global project.

Thanks in advance 😃 

Sincerely,
@wikijm

**Comment by acicalla** [comment]
You need to look at scheduled tasks. It creates a few of them that you need to remove.

**Comment by mwanza-k** [comment]
> You need to look at scheduled tasks. It creates a few of them that you need to remove.

any guidance on this?

**Comment by Neo23x0** [comment]
I will extend the red message, that pops up at the beginning and add the recommendation to create a snapshot of that test system
https://github.com/NextronSystems/APTSimulator#warning

**Comment by acicalla** [comment]
> > You need to look at scheduled tasks. It creates a few of them that you need to remove.
> 
> any guidance on this?

It's really not that difficult. In the search box on your windows machine type "task scheduler" and there are several tasks added and all you need to do is remove them and the APT activity will stop.

**Comment by Neo23x0** [comment]
Mhhh ... the WMI backdoor may require some additional attention. 
https://github.com/NextronSystems/APTSimulator/blob/master/test-sets/persistence/wmi-backdoor.bat

**Comment by acicalla** [comment]
The AV/EDR tools we used blocked all of the PowerShell execution so that wasn't an issue for us. The only thing was the scheduled tasks that kept running. Once they were removed we had no more activity on the system. You can use Get-ScheduledJob, and Get-ScheduledTask to find and remove any PowerShell tasks. 

Why not just add a 'clean-up' script that removes the tasks that are added?

**Comment by Neo23x0** [comment]
> Why not just add a 'clean-up' script that removes the tasks that are added?

Simple. It don't have enough time. Other projects require my attention more urgently. 
I gladly accept pull requests.

**Comment by mwanza-k** [comment]
i used the below, maybe it can help someone

Get-WMIObject -Namespace root\Subscription -Class __EventFilter -Filter "Name='TimingIntervalTrigger'" | Remove-WmiObject -Verbose
Get-WMIObject -Namespace root\Subscription -Class __FilterToConsumerBinding -Filter "__Path LIKE '%TimingIntervalTrigger%'" | Remove-WmiObject -Verbose
Get-WMIObject -Namespace root/Subscription -Class ActiveScriptEventConsumer -Filter "Name='LaunchBeaconingBackdoor'" | Remove-WMIObject -Verbose
