### ISSUE TITLE
Test-Sets documentation

### ISSUE THREAD

**Issue by tophertimzen** [NextronSystems/APTSimulator#5]
When downloading a release there is a `test-sets` directory with categories such as `collection`, `discovery`, etc, but the `README` describes "Test Cases". It would be nice if those 22 test cases were put into the categories you will find in `test-sets` on a release package. The same goes for the test sets that aren't documented in those 22 test cases (not sure if they all are). With that, the "Extending the Test Set" section of the `README` should suggest documenting the new test set in that "Test Case" section.

**Comment by Neo23x0** [comment]
Done

**Comment by tophertimzen** [comment]
Fantastic! Looks great now and is way more intuitive!
